[package]
name = "toph"
version = "1.0.0"
description = "a minimal, extensible pixel editor"
license = "unlicense"
repository = "https://github.com/Dream-Imperium/toph"
homepage = "http://dreamimperium.tk/toph.html"
authors = ["Dream Imperium Team <mail@dreamimperium.tk>"]
edition = "2018"

[features]
default = ["glfw"]

[dependencies]
pico-args = "0.3.0"
simple_logger = { version = "1.4.0", default-features = false }
png = { version = "0.16.6" }
gif = "0.10.3"
glfw = { version = "0.36.0", optional = true }
raw-window-handle = { version = "0.3.3", optional = true }
zip = { version = "0.5.5", default-features = false, features = ["deflate", "flate2"] }
snap = "0.2.5"
log = "0.4.6"
directories = "2.0.2"
seahash = "4.0.0"
digest = "0.8.1"
nonempty = "0.1.4"
memoir = "0.2.1"
miniserde = "0.1"
arrayvec = "0.5"
luminance = "0.40.0"
luminance-gl = "0.14.0"
luminance-derive = "0.6.0"
gl = "0.14"

[dependencies.rgx]
version = "0.8.1"

[dev-dependencies]
lazy_static = "1.3"
tempfile = "3"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
